language:
  python

addons:
  apt:
    packages:
    - python-wxversion
    - python-wxgtk2.8

install:
  - sudo pip install bcrypt
  - sudo pip install requests
  - sudo pip install SQLAlchemy
  - sudo pip install sqlalchemy-utils
  - sudo pip install future
  - sudo pip install configparser

script:
  - cd tests && sudo python ./nonreg.py -v